image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy:
  stage: deploy
  script:
    - apk add openssh
    - echo "$SSH_KEY" > ssh.key
    - chmod 600 ssh.key
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ssh.key  -p18022 dockeru@zoobab.serveo.net docker pull registry.gitlab.com/zoobab/arduino-cli-esp8266
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ssh.key  -p18022 dockeru@zoobab.serveo.net docker run --privileged registry.gitlab.com/zoobab/arduino-cli-esp8266