apiVersion: v1
kind: Pod
metadata:
  generateName: arduinocli-
spec:
  imagePullPolicy: Always
  restartPolicy: Never
  containers:
  - image: registry.gitlab.com/zoobab/arduino-cli-esp8266
    name: arduinocli
    securityContext:
      privileged: true
